### ISSUE TITLE
The number of layers and hidden dim are fixed in the CUDA implementation

### ISSUE THREAD

**Issue by licj15** [creiser/kilonerf#19]
Hi Christian @creiser !

Thank you a lot for the great work and the open-sourced code! It is very helpful in the NeRF community!

I noticed that **the number of layers and hidden dims seems to be fixed** in [the CUDA implementation](https://github.com/creiser/kilonerf/blob/master/cuda/network_eval.cu), regardless of the number of layers and hidden dim we set in the .yaml file.

If I understand it correctly:

- [this part](https://github.com/creiser/kilonerf/blob/master/cuda/network_eval.cu#L278-L291) fixed the hidden dims to be 32
- [this part ](https://github.com/creiser/kilonerf/blob/master/cuda/network_eval.cu#L42-L46) fixed the number of layers to be 5. 

 I was wondering:
- **The reason why you fixed them here** (for less pre-allocated memory?) 
- Do you have any plan to extend it to support an arbitrary number of layers and hidden dim?

Thank you!

**Comment by creiser** [comment]
We fixed that here because the [compiler can only store arrays whose size is known at compile-time in registers.](https://developer.nvidia.com/blog/fast-dynamic-indexing-private-arrays-cuda/) You can add more layers by adding more matrix multiplications in `network_eval.cu`. A more general solution would be to use meta-programming in order to generate code for a variety of hyperparameters. Different number of hidden dims are supported by simply adding additional cases here: https://github.com/creiser/kilonerf/blob/master/cuda/network_eval.cu#L278-L291

You cannot indefinitely increase the param count since with the current implementation it is required that a network fully fits into shared memory and this is crucial for performance. For instance, a GTX 1080 Ti has 96 KB of shared memory, so you can fit a maximum of 24000 parameters. The default architecture only requires 6212 parameters. Also by increasing the hidden dim too much you would use too many registers which limits occupancy.
